<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>LegalEase - AI Legal Generator</title>
<script src="https://cdn.tailwindcss.com"></script>
</head>
<body class="bg-[#f8f9ff] min-h-screen">
<div class="max-w-6xl mx-auto p-4 md:p-8">
<h1 class="text-3xl font-bold text-center">LegalEase ⚖️ - AI Powered Document Generator</h1>
<p class="text-center text-gray-500 mt-2">Model: gemini-1.5-pro | Workflow: User Input -> AI -> Document</p>

<div class="grid grid-cols-1 md:grid-cols-2 gap-6 mt-8">
<!-- LEFT FORM -->
<div class="bg-white p-6 rounded-xl shadow-lg">
<h2 class="font-bold text-lg mb-4">1. Document Details</h2>

<label class="text-sm font-medium">Document Type</label>
<select id="docType" class="w-full border p-3 rounded-lg mt-1 mb-4">
<option>Non-Disclosure Agreement (NDA)</option>
<option>Rental Agreement</option>
<option>Employment Offer Letter</option>
<option>Partnership Deed</option>
<option>Freelance Contract</option>
</select>

<label class="text-sm font-medium">Party 1 Name (Disclosing / Owner)</label>
<input id="party1" type="text" placeholder="Ex: ABC Pvt Ltd" class="w-full border p-3 rounded-lg mt-1 mb-4">

<label class="text-sm font-medium">Party 2 Name (Receiving / Tenant)</label>
<input id="party2" type="text" placeholder="Ex: John Doe" class="w-full border p-3 rounded-lg mt-1 mb-4">

<label class="text-sm font-medium">Effective Date & City</label>
<div class="flex gap-2 mt-1 mb-4">
<input id="date" type="date" class="w-1/2 border p-3 rounded-lg">
<input id="city" type="text" placeholder="City, Ex: Tirupur" class="w-1/2 border p-3 rounded-lg">
</div>

<label class="text-sm font-medium">Key Terms / Clauses</label>
<textarea id="terms" rows="4" placeholder="Ex: 2 years confidentiality, Rs 50000 rent, 11 months..." class="w-full border p-3 rounded-lg mt-1 mb-4"></textarea>

<button onclick="generateDoc()" id="genBtn" class="w-full bg-black text-white p-4 rounded-lg font-bold hover:bg-gray-800">
✨ Generate with Gemini AI
</button>
<p class="text-xs text-center mt-3 text-gray-400">Powered by Gemini 1.5 Pro API</p>
</div>

<!-- RIGHT PREVIEW -->
<div class="bg-white p-6 rounded-xl shadow-lg border-2 border-dashed">
<h2 class="font-bold text-lg mb-4">2. AI Generated Document</h2>
<div id="preview" class="bg-gray-50 p-6 rounded-lg min-h-[400px] text-sm whitespace-pre-wrap font-serif leading-relaxed">
Your legal document will appear here after generation...
</div>
<div class="flex gap-2 mt-4">
<button onclick="downloadPDF()" class="flex-1 bg-blue-600 text-white p-3 rounded-lg font-bold">📄 Download PDF</button>
<button onclick="copyText()" class="flex-1 border p-3 rounded-lg font-bold">Copy</button>
</div>
</div>
</div>
</div>

<script>
async function generateDoc(){
  const btn = document.getElementById('genBtn');
  const preview = document.getElementById('preview');
  const docType = document.getElementById('docType').value;
  const p1 = document.getElementById('party1').value;
  const p2 = document.getElementById('party2').value;
  const date = document.getElementById('date').value;
  const city = document.getElementById('city').value;
  const terms = document.getElementById('terms').value;

  if(!p1 ||!p2){ alert('Party 1 & Party 2 fill pannu da'); return; }

  btn.innerText = 'Generating... Please wait ⏳';
  btn.disabled = true;

  // --- DEMO MODE (AI Studio key illana kooda work aagum) ---
  const demoContent = `
${docType.toUpperCase()}
This Agreement is made on ${date || new Date().toLocaleDateString()} at ${city || 'Tirupur'}

BETWEEN:
${p1} (Hereinafter referred to as "First Party")

AND:
${p2} (Hereinafter referred to as "Second Party")

1. PURPOSE:
This ${docType} is created for the purpose of ${terms || 'mutual business understanding'}.

2. CONFIDENTIALITY / TERMS:
Both parties agree to maintain confidentiality and abide by all terms mentioned.
a) The receiving party shall not disclose any confidential information.
b) This agreement shall be governed by laws of India, jurisdiction at ${city}.

3. DURATION:
This agreement shall be effective from ${date} and shall continue as per mutually agreed terms.

4. SIGNATURE:

For ${p1} For ${p2}

_________________ _________________
(Authorized Signatory)

[Generated by LegalEase using gemini-1.5-pro Model - Architecture: Frontend -> FastAPI -> Gemini API]
`;

  // Simulate AI delay
  setTimeout(()=>{
    preview.innerText = demoContent;
    btn.innerText = '✨ Generate with Gemini AI';
    btn.disabled = false;
  }, 1500);

  // --- REAL GEMINI API CODE (Uncomment after getting API Key from AI Studio) ---
  /*
  const API_KEY = "YOUR_GEMINI_API_KEY_HERE";
  const prompt = `You are a legal expert. Create a professional ${docType} between ${p1} and ${p2} dated ${date} at ${city} with terms: ${terms}. Use Indian legal format.`;
  const response = await fetch(`https://generativelanguage.googleapis.com/v1beta/models/gemini-1.5-pro:generateContent?key=${API_KEY}`, {
    method: 'POST',
    headers: {'Content-Type':'application/json'},
    body: JSON.stringify({contents:[{parts:[{text:prompt}]}]})
  });
  const data = await response.json();
  preview.innerText = data.candidates[0].content.parts[0].text;
  */
}

function downloadPDF(){
  const text = document.getElementById('preview').innerText;
  const win = window.open('', '', 'height=700,width=800');
  win.document.write('<html><head><title>LegalEase Document</title></head><body><pre style="font-family: serif; white-space: pre-wrap;">' + text + '</pre></body></html>');
  win.document.close();
  win.print();
}
function copyText(){
  navigator.clipboard.writeText(document.getElementById('preview').innerText);
  alert('Copied da!');
}
</script>
</body>
</html>
